### ISSUE TITLE
Circle tab not honoring diameter drop-down

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#473] opened 2017-12-08 00:26 UTC
On the Distance and Direction tab of the Military Tools add-in for ArcMap 10.6 (8318) the circle tab is always using the Radius/Diameter value as the radius of the cricle, regardless of what is selected in the "From" drop-down. It is then labeling it as diameter, which is technically correct, it did draw a circle with diameter 400, but the expected behavior is that if i enter 200 and have diameter selected, then the diameter would be 200, not 400.
![image](https://user-images.githubusercontent.com/5322669/33745239-8483c9ae-db6a-11e7-8e44-6edd6fc6a0e1.png)
( I have  a value of 200 miles entered, and Diameter selected)
![image](https://user-images.githubusercontent.com/5322669/33745351-3c58cb10-db6b-11e7-9d9b-490b0b1c3c68.png)
(output circle is diameter 400 when i wanted a diameter 200, any value being input is being treated as a radius)

**Comment by dfoll** [comment] 2017-12-08 00:29
Can @ACueva @topowright please verify this is legit
Could @lfunkhouser please prioritize? my inclination is that this still passes certification, because I don't believe this is something the core has broken for us

**Comment by BobBooth** [comment] 2017-12-08 15:48
https://github.com/Esri/distance-direction-addin-dotnet/issues/448

**Comment by BobBooth** [comment] 2017-12-08 15:49
https://github.com/Esri/distance-direction-addin-dotnet/issues/449

**Comment by lfunkhouser** [comment] 2017-12-08 18:12
@dfoll @BobBooth was this an issue with the released solution on 10.3.1-10.5.1? Or is it something that just happened? Have you worked with @csmoore to provide additional details as to why this is happening?

**Comment by lfunkhouser** [comment] 2017-12-08 18:17
Closing. This is a duplicate of #448 and #449.

**Closed by lfunkhouser** 2017-12-08 18:17 UTC
Labels: A-bug, F - circles, FT-Military Tools, G - Defense Team, G-Development, G-Documentation Review, Military Tools, priority - normal, V - 10.6
