### ISSUE TITLE
Graphics are not cleared until map is refreshed (ArcMap)

### ISSUE THREAD

**Issue by Thargoids** [Esri/distance-direction-addin-dotnet#206] opened 2016-12-21 17:53 UTC
**Procedure**

1. Create point with Circle tab
2. Enter a value in Radius / Diameter
3. Press Enter
4. Click Clear Graphics

**Result**

Graphics are not cleared from map

**Result expected**

Graphics are cleared from map

**Comment by pHill5136** [comment] 2016-12-28 19:43
@nfeuerstein @Thargoids  Unable to reproduce. The  graphics are clearing for me.... Sending to verify. See if anyone else sees this issue...

**Comment by Thargoids** [comment] 2017-01-04 17:41
This could be down to my dev VM. My laptop profile is locked down else I would install ArcMap locally to test. Perhaps better to assign to someone else to test on a different environment to mine? Alternatively since it seems I'm the only one seeing this, perhaps we should go with the majority and close it as not reproducible?

**Comment by mfunk** [comment] 2017-01-04 18:32
Tried this on todays build of the Add-Ins on 10.3.1 and the graphics are cleared on all tabs immediately after graphic is drawn.
Closing as non-repro.

**Closed by mfunk** 2017-01-04 18:32 UTC
Labels: 3 - Verify, priority - normal, V - 10.3.1
