### ISSUE TITLE
BUG-000120038  The Military Tools Distance and Direction tool does not work in a .mxd file if it contains data projected to British National Grid.

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#666] opened 2019-02-24 17:16 UTC
<div><div>
<span><b>Salesforce ID:</b> <a href="https://qamonitor/SFTriage?sfid=BUG-000120038">BUG-000120038</a></span><br/>
<span><b>Salesforce Submitter:</b> Margaret Maher</span><br/>
<span><b>Salesforce Submit Date:</b> 2/12/2019 3:37 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000120038</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Defense</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.6.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by dfoll** [comment] 2019-07-22 13:11
### Synopsis:
The Military Tools Distance and Direction tool does not work in a .mxd file if it contains data projected to British National Grid.
Steps to Repro:
1]  Open "Copy_of_ESRI Sample Map.mpk", which contains several layers of data, including one layer, OS_Open_Raster basemap, which is projected to British National Grid (BNG).
In the Distance and Direction dialog, attempt to create a line.  This will not work, with the raster projected to BND in the map document.

2]  Open "ESRI Sample map remove openraster.mpk" from which the OS_Open_Raster basemap has been removed.
Using the Distance and Direction dialog, you will find that you can create lines all over the map, and save to a shapefile or geodatabase feature class.

3]  Open "ESRI Sampe map add BNG layer.mpk" which contains a vector layer gb_counties_BNG.shp.  Again, with data in the map projected to British National Grid, a Distance and Direction line cannot be created.
I added this vector data, to confirm that the problem was with the British National Grid coordinate system, and not the raster basemap.

**Comment by dfoll** [comment] 2019-08-09 12:48
@CTLocalGovTeam is having some issues repro-ing this issue. it is requested that our team confirm it can be reproduced.

**Comment by dfoll** [comment] 2019-08-16 14:08
As written I could not repro this by explicitly following the steps. We have seen a known limitation in the past when dealing with [graphics and changing the data frame coordinate system](http://qamonitor/qacommon/crlookup.aspx?cr=BUG-000114828) on versions 10.5.1- 10.7.  If there are some other implied steps for this repro case that were not explicitly stated, this is likely related/the same issue.

If the problem is meant to be reproducible with the explicit steps given above, the ArcGIS for Defense team will need more information to fix this.

**Comment by dfoll** [comment] 2019-08-16 20:30
I will be reaching out to Margaret to get more info

**Comment by dfoll** [comment] 2019-08-19 23:26
I reached out to Margaret and she vaguely remembered working on this issue, but did not recall specifics. We could not repro together. the only case we could repro was when we changed the coordinate system of the data and encountered [this core issue](http://qamonitor/qacommon/crlookup.aspx?cr=BUG-000114828). I zipped up a map package that is saved in British National Grid, showing that if you don't have to change the data frame (all the examples given start in Web Mercator) the issue is not reproducible.

I think this should be closed as non-reproducible.

[Updated_DD_issue_sample_data.zip](https://github.com/Esri/distance-direction-addin-dotnet/files/3518050/Updated_DD_issue_sample_data.zip)

**Closed** 2019-09-13 14:42 UTC
Labels: A-bug, CT-Awaiting response, CyberTech, G-Development, G-Doc (CMS), G-QC (Doc), G-QC Verify (Manual), Support
