### ISSUE TITLE
Clear Graphics buttons on Distance and Direction Add-in delete all graphics

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#177] opened 2016-12-14 22:10 UTC
_From @topowright on December 8, 2016 23:6_

Clear Graphics buttons on Distance and Direction Add-in delete all graphics

## Expected Behavior
Each Graphics button only deletes the graphics from that tab

## Current Behavior
All graphics are delted when using the Clear Graphics button

## Steps to Reproduce (for bugs)

1.Create graphics on two differnt tabs
2. click the Clear Graphics button
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#80_

**Comment by nfeuerstein** [comment] 2016-12-14 23:57
Is this issue closed?  I'm seeing several bugs that were logged in military-tools-for-arcgis that are referenced in this repo.  The referenced bug is closed but this one is still open.  It's confusing.

**Comment by elinz** [comment] 2016-12-15 16:10
@nfeuerstein All of the issues that were in the https://github.com/Esri/military-tools-for-arcgis repo were moved to the individual component repo's since the tools are still individual components.

**Comment by pHill5136** [comment] 2016-12-15 21:01
@nfeuerstein @topowright Fixed this. pull request https://github.com/Esri/distance-direction-addin-dotnet/pull/183 . Clear graphics clears only graphics associated with the active tab.

**Comment by mfunk** [comment] 2016-12-15 22:35
Was this for both Pro and ArcMap, or just ArcMap?

**Comment by mfunk** [comment] 2016-12-15 22:59
Tested on ArcMap 10.3.1, ArcMap 10.4, and Pro 1.3 and all good.
Need to install Pro 1.4 and test there next.

**Comment by mfunk** [comment] 2016-12-15 23:02
Dang it. Tested on 1.4 already, not 1.3. Need to go back and try again on 1.3.

**Comment by mfunk** [comment] 2016-12-16 15:11
Good to go.

**Comment by mfunk** [comment] 2016-12-16 21:37
Reopened because PR hasn't gone through yet, but somehow the problem is now gone.

**Comment by mfunk** [comment] 2016-12-19 18:39
So this one is fixed and was done so in an earlier PR than the aforementioned #183. Closing.

**Closed by mfunk** 2016-12-19 18:39 UTC
Labels: 0 - Backlog, B - Bug
