### ISSUE TITLE
Holistic Testing: Loading layer package prompts Save Project As

### ISSUE THREAD

**Issue by mfunk** [Esri/distance-direction-addin-dotnet#675] opened 2019-08-12 16:07 UTC
From Holistic Testing 8/9/2019:

onenote:///\\tahoe\holistic\ArcGISProfessional\Srinivas\Pro_v2_5\ProInternalHolistic_v2_5\August2019\Friday_08_09_2019.one#Pro%20for%20Intel&section-id={F5163543-00ED-4E04-962A-EF349811C6D0}&page-id={495373F4-9079-4A22-A025-E02A20F312F4}&end

Row 17, Tester Kory K.

![image](https://user-images.githubusercontent.com/3093182/62879651-77326b80-bce0-11e9-8070-4877925c7f26.png)

![image](https://user-images.githubusercontent.com/3093182/62879660-7c8fb600-bce0-11e9-98a1-97bf0cbc060c.png)

![image](https://user-images.githubusercontent.com/3093182/62879691-8fa28600-bce0-11e9-9456-1e5dbdf669f4.png)

**Comment by lfunkhouser** [comment] 2019-09-16 22:55
@mfunk Can you provide specific steps to reproduce? I'm not getting prompted to Save Project As...

1. Open ArcGIS Pro for Intelligence
2. Select New Blank Map Template
3. Accept Default values for Name and Location in Create a New Project dialog > Click OK
4. Open Distance and Direction tool from Inquiry section of Map ribbon
5. Leave default values for Line Type (Geodetic) and From: (Points)
6. Click to enable the Map Point Tool
7. Click on the map to select the Starting Point
8. Click on the map for Ending Point
Result: Loading required layer Package dialog pops up and feature drawn and labeled

ArcGIS Pro 2.5.0 21541
ArcGIS Pro for Intelligence 2.5.0 Build 1391

**Comment by lfunkhouser** [comment] 2019-09-18 15:36
Closing. Unable to reproduce the issue using the workflow I provided.

**Closed by lfunkhouser** 2019-09-18 15:36 UTC
Labels: A-bug, B-moderate, E-non reproducible
