### ISSUE TITLE
Create Circle from distance calculator result always labeled with Radius in ArcMap

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#449] opened 2017-09-27 17:24 UTC
When I define a point with the "From" set to "Diameter", then use the distance calculator and set the time and rate (in this case, Time: 60 hours, Rate 10 M/H), I get an output with a radius 600 meters, labeled Radius: 600 M.  Given the fact that the "From" was set to "Diameter", I would at least expect the label to say  Diameter: 1200 M, which would match the (questionable, see Create Circle from Radius/Diameter only affects labeling, not size of circle - unexpected #448) behavior of the tool
![image](https://user-images.githubusercontent.com/3801392/30927470-939de4b8-a386-11e7-8ca5-b3b5ea3985c2.png)

Testing on ArcMap 10.6, Distance and Direction Add-In 2.1.1

**Comment by BobBooth** [comment] 2017-09-29 18:41
This is also an issue in the combined add-in, Military Tools 2.0

**Comment by lfunkhouser** [comment] 2017-12-08 18:18
@dfoll Also found and logged this issue. I closed it due to being a duplicate. @dfoll @BobBooth was this an issue with the released solution on 10.3.1-10.5.1? Or is it something that just happened? Have you worked with @csmoore to provide additional details as to why this is happening?

**Comment by topowright** [comment] 2017-12-12 03:10
I have confirmed that this same issue is with the released version of the product. I also have verified that if you run the tool with radius or diameter the tool produces the same outputs. 

![image](https://user-images.githubusercontent.com/5488313/33865529-033be9ea-dea7-11e7-9b05-2ffdbaf5b5c3.png)

**Comment by topowright** [comment] 2018-01-10 17:28
- [ ] Configured at the component level
- [ ] Configured at Military Tools for ArcGIS

**Comment by csmoore** [comment] 2018-01-11 14:29
The bug fix has been done in commit / branch :
 
https://github.com/Esri/distance-direction-addin-dotnet/commit/b6293dd6070b53b57766f5f4e3c732bdbb9bacc6  /  
https://github.com/Esri/distance-direction-addin-dotnet/tree/csm/%23449-bad-label-on-calc-circle 

Removing dev label and looking into unit test possibilities of testing this internal method: 
https://github.com/Esri/distance-direction-addin-dotnet/blob/dev/source/addins/ArcMapAddinDistanceAndDirection/ArcMapAddinDistanceAndDirection/ViewModels/CircleViewModel.cs#L811 

But there does not appear to be anything changed external to this method to test so this may not be a good unit test candidate.

**Comment by csmoore** [comment] 2018-01-11 15:01
@topowright @ACueva - I created an __intentionally-failing__ test case for if/when you want to test that the framework is capturing failures correctly - in this branch:

https://github.com/Esri/distance-direction-addin-dotnet/blob/csm/%23449-force-unit-test-fail

Failing case:

https://github.com/Esri/distance-direction-addin-dotnet/blob/csm/%23449-force-unit-test-fail/source/addins/ArcMapAddinDistanceAndDirection.Tests/ArcMapAddinDistanceAndDirectionTests.cs#L274

**Comment by ACueva** [comment] 2018-01-11 21:17
Working on verifying fail case from within Jenkins.

**Comment by csmoore** [comment] 2018-01-11 22:44
Added IsDistanceCalcExpanded test in https://github.com/Esri/distance-direction-addin-dotnet/commit/e6901817bd830c043186360f49ad0685aa1f6412 to test diameter vs. radius

**Comment by ACueva** [comment] 2018-01-11 23:53
Distance and Direction unit tests are now included in the military-tools-for-arcgis-build project.  These tests run automatically after creating the Distance and Direction add-in.

```
15:28:40 Loading ArcMapAddinDistanceAndDirection.Tests.dll...
15:28:40 Starting execution...
15:29:14 
15:29:14 Results               Top Level Tests
15:29:14 -------               ---------------
15:29:14 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel
15:29:14 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_IsDistanceCalcExpanded
15:29:14 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException
15:29:15 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException10
15:29:15 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException11
15:29:15 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException2
15:29:15 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException3
15:29:15 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException4
15:29:15 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException5
15:29:15 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException6
15:29:15 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException7
15:29:15 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException8
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException9
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException2
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException3
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException4
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException5
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException6
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException7
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException8
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException2
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException3
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException4
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException5
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException6
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException7
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LineViewModel
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel_ThrowsException
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel_ThrowsException2
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel_ThrowsException3
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel_ThrowsException4
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel_ThrowsException5
15:29:16 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel_ThrowsException6
15:29:16 37/37 test(s) Passed
15:29:16 
15:29:16 Summary
15:29:16 -------
15:29:16 Test Run Completed.
15:29:16   Passed  37
15:29:16   ----------
15:29:16   Total   37
15:29:16 Results file:  c:\jenkins\workspace\military-tools-for-arcgis-build\distance-direction-addin-dotnet\source\addins\ArcMapAddinDistanceAndDirection.Tests\bin\Release\TestResults\avel5840_SOLWIN07-J03 2018-01-11 15_28_40.trx
```

**Comment by ACueva** [comment] 2018-01-11 23:58
Tested the build using a different branch @csmoore created specifically to test:

```
15:49:36 Loading ArcMapAddinDistanceAndDirection.Tests.dll...
15:49:37 Starting execution...
15:50:10 
15:50:10 Results               Top Level Tests
15:50:10 -------               ---------------
15:50:10 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel
15:50:10 Failed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_GuarenteedFail
15:50:10 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException
15:50:10 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException10
15:50:10 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException11
15:50:10 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException2
15:50:10 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException3
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException4
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException5
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException6
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException7
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException8
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.CircleViewModel_ThrowsException9
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException2
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException3
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException4
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException5
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException6
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException7
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.EllipseViewModel_ThrowsException8
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException2
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException3
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException4
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException5
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException6
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LinesViewModel_ThrowsException7
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.LineViewModel
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel_ThrowsException
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel_ThrowsException2
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel_ThrowsException3
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel_ThrowsException4
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel_ThrowsException5
15:50:11 Passed                ArcMapAddinDistanceAndDirection.Tests.ArcMapAddinDistanceAndDirectionTests.RangeViewModel_ThrowsException6
15:50:11 36/37 test(s) Passed, 1 Failed
15:50:11 
15:50:11 Summary
15:50:11 -------
15:50:11 Test Run Failed.
15:50:11   Passed  36
15:50:11   Failed   1
15:50:11   ----------
15:50:11   Total   37
15:50:11 Results file:  c:\jenkins\workspace\military-tools-for-arcgis-build\distance-direction-addin-dotnet\source\addins\ArcMapAddinDistanceAndDirection.Tests\bin\Release\TestResults\avel5840_SOLWIN07-J03 2018-01-11 15_49_37.trx
```
The tests, even with failures are not triggering an error on the Jenkins side.  Will log an issue to address this.

**Comment by topowright** [comment] 2018-01-12 02:12
@ACueva I feel like this is not done until this lives in a project that is attached to a pipeline not attached to the old projects.

**Comment by topowright** [comment] 2018-01-12 20:21
This is the location of the test that fails: 
https://github.com/Esri/distance-direction-addin-dotnet/blob/csm/%23449-force-unit-test-fail/source/addins/ArcMapAddinDistanceAndDirection.Tests/ArcMapAddinDistanceAndDirectionTests.cs

**Comment by topowright** [comment] 2018-01-16 18:28
We might need to see if we can test this using MS Test. @ACueva can you add more info to this if needed

**Closed** 2018-04-30 08:55 UTC
Labels: A-bug, B-high, E-verified, F - circles, S-Military Tools, V - 10.3.1, V - MT 3.0
