### ISSUE TITLE
Using add-in with existing ArcGIS Pro project at a different scale causes "Spatial Index Grid Size" error 

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#648] opened 2019-02-22 17:12 UTC
Repro steps:

1. Create a new Pro project
2. Zoom into the Monterey Peninsula
3. Create a line, circle, ring the approximate size of the peninsula
4. Exit Pro (Save the Project)
5. Run Pro and open the previously created project
6. Zoom to world scale
7. Attempt to create a line at world scale
8. "Spatial Index Grid Size is Invalid" Error is reported and line can't be created

![image](https://user-images.githubusercontent.com/3090809/53256757-9f78d000-3696-11e9-83e3-cc1ef7913aa8.png)

We have seen this error before in Pro with lpkxs ( https://github.com/Esri/military-features-data/issues/287 ) - but this issue is slightly different, it seems like when you save a Pro project it is setting a spatial index on the GDB, not sure if this is a new issue at Pro 2.3, or we just never noticed previously.

Note: I confirmed that these steps also create the same failure with the Military Symbol Editor (create a Military Line symbol instead of a D&D line)

**Comment by lfunkhouser** [comment] 2019-02-22 21:03
Need to check on previous version of Pro to see if this is a Pro 2.3 change.

**Comment by csmoore** [comment] 2019-05-31 15:54
Testing this on 2.4 and I am experiencing some lockups loading the layer package and activating the Map Tool at full extent (I don't see this on my 2.2 machine) - so investigating this

**Comment by csmoore** [comment] 2019-05-31 21:48
On Pro 2.4.19901 I am seeing an issue where when I try to draw the first graphic, the map zooms to full extent and then when I manually zoom back to the original area, 3 graphics are draw.  
@saip can you try this on your latest Pro build?

![image](https://user-images.githubusercontent.com/3090809/58736451-eda31b00-83cb-11e9-94b7-bf5039789802.png)

**Comment by csmoore** [comment] 2019-06-06 21:37
@saip - @ljuru and I stepped through the repro steps in the original issue on Pro 2.4.19921 on 2 different machines but we are still seeing the lockup issue [mentioned previously](https://github.com/Esri/distance-direction-addin-dotnet/issues/648#issuecomment-497762117) - can you try this?

**Comment by csmoore** [comment] 2019-06-11 13:58
Verified that with PR #658 the error is not received - still investigating a possible deadlock issue on 2.4 unrelated to this PR

**Comment by csmoore** [comment] 2019-06-11 20:33
I was able to reproduce the lockup issue outside of the D&D addin, so I do not believe it is related to our addin and we will pass these repro-steps onto the Pro team (both @dfoll and I repro'd this issue)

Repro Steps:

1. Open the Pro Package provided in Pro 2.4 (tested on version after 2.4.19921) - ["Test-DD-Lockup.ppkx.zip"](https://github.com/Esri/distance-direction-addin-dotnet/files/3278445/Test-DD-Lockup.zip)
2. Click the Full Extent Button
3. Click the Insert Tab
4. The UI behaves strangely, some things work, but the tools are all grayed out and none of the tools can be selected

**Comment by williamscraigm** [comment] 2019-06-14 20:53
Core issue logged as https://devtopia.esri.com/ArcGISPro/text/issues/1876

**Comment by dfoll** [comment] 2019-06-21 20:22
We believe this was fixed in Pro 2.4 final. We believe this only needs to be confirmed as fixed and then listed as an issue addressed

**Comment by dfoll** [comment] 2019-06-22 14:04
### ArcGIS Pro 2.4.0 b1 (19489) + DD build 91
- could not reproduce problem with repro steps in the original issue, but could reproduce the problem with the repro steps in [this comment](https://github.com/esri/distance-direction-addin-dotnet/issues/648#issuecomment-501011875)

### ArcGIS Pro 2.4.0. +DD build 91
-

**Comment by dfoll** [comment] 2019-06-22 14:45
certification test updated in [this pr](https://github.com/ArcGIS/solutions-defense-test-catalog/pull/222)

**Comment by dfoll** [comment] 2019-06-22 15:05
- https://solutionsdev.arcgis.com/defense/help/distance-direction/resources/june-2019-distance-and-direction.htm
- \\...\DefenseSolutions\DistanceAndDirection\Dev\92\
- 
-

**Comment by lfunkhouser** [comment] 2019-06-24 20:43
Verified in issues addressed for DD and MT on staging
Verified in PDFs in dev builds of DD 95 and MT 313

**Closed by lfunkhouser** 2019-06-24 20:43 UTC
Labels: A-bug, B-Showstopper, CT-Fixed, CyberTech, E-verified, V - MT 3.5, V - Pro2.2

**Comment by dfoll** [comment] 2020-03-25 17:14
this issue may have crept back in for arcgis pro 2.6. have not done a ton of research at this point....info for build that made me think this is 2.6.23.681 and  ArcGIS.Desktop.Defense built on 24March. Couldn't immediately repro without spending time dedicated to sitting down and reproing, but i did notice this message. first step will be trying the repro steps in this issue.
