### ISSUE TITLE
Error with features when saving to KML

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#366] opened 2017-05-08 17:20 UTC
The following feaures were saved as KML.
![image](https://cloud.githubusercontent.com/assets/5116835/25816159/0a73335a-33d8-11e7-97ff-ce6579914c1f.png)
This is how they look in ArcGIS Earth
![image](https://cloud.githubusercontent.com/assets/5116835/25816183/25494d7c-33d8-11e7-9e6f-1d131101f51d.png)
Unsure what could be causing the issue.

**Comment by NatalieCampos** [comment] 2017-05-08 19:21
@lfunkhouser @nfeuerstein

**Comment by pHill5136** [comment] 2017-05-09 21:50
I am unable to consistently reproduce this issue. Most tests my kmls export without error. I have seen occasions where the kml appears to be corrupted. It seems to be occurring inside the gptool...

**Comment by nfeuerstein** [comment] 2017-05-18 16:53
Try passing output shapefile to GP Tool to see if this is an issue with how we call the GP tool or if its an issue with the GP tool.

**Comment by pHill5136** [comment] 2017-05-19 16:10
@nfeuerstein @kgonzago @NatalieCampos We tried saving to kmz with the gptool. I had success. We tried with Avi's computer and we got a corrupted kmz. So this tells us that the problem is with the gp tool. Avi is opening a support issue since he has a reproducible case.

**Comment by lfunkhouser** [comment] 2017-12-08 18:25
@ACueva Did you open a support issue? Please provide the issue number.

**Comment by ACueva** [comment] 2017-12-08 18:32
@lfunkhouser No support ticket was logged.  In certifying Pro 2.1 I've been verifying kml results and no longer see this behavior.

**Comment by lfunkhouser** [comment] 2017-12-08 18:40
Per @ACueva This is non-reproducible. Closing issue.

**Closed by lfunkhouser** 2017-12-08 18:40 UTC
Labels: A-bug, C-L, E-non reproducible
