### ISSUE TITLE
Saving Distance and Direction Graphics as KMZ - Bad Outputs

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#360] opened 2017-03-24 21:07 UTC
Trying to save out some Distance and Direction graphics as a KMZ from ArcGIS Pro 1.4, and I'm able to save the graphics, but they are not being added to the table of contents, nor are they visible once I do add them to the table of contents. 

When I open these kmz files in ArcGIS Earth, this is what I found:

![image](https://cloud.githubusercontent.com/assets/13024357/24313541/722b8ef4-109a-11e7-8528-87ac6b494c12.png)

To reproduce: 
1. Open the Distance and Direction tool in ArcGIS Pro 1.4
2. Create circle, line, ellipse, and range ring graphics. 
3. save these features out as a kmz file
4. try and add the kmz files to the map - I was unable to see anything and when I clicked zoom to layer the map went out to a global extent
5. try and add the kmz files in arcgis earth. 

I think this is a similar issue to #329, except that I can't get the kmz to save out properly. 

Anyone else having trouble saving these as kmz files as of late? @mfunk did you take any further look at this?

**Comment by mfunk** [comment] 2017-03-24 21:17
@Dbarnes1 I did not as I don't have much experience with KML/KMZ files.

**Comment by BobBooth** [comment] 2018-01-23 20:51
Is this a core Layer to KMZ issue?

**Comment by BobBooth** [comment] 2018-02-15 21:04
I am not able to reproduce this issue with Pro 2.1 and the Military Tools for ArcGIS Pro 2.0 add-in.
I think that the logic for the way graphics are stored and exported (and possibly the core export to KMZ tool) has changed since this issue was submitted.  I am only seeing graphics of the current DD tab type (Line, Circle, Ellipse, Ring) being exported, even when multiple geometries/types are on the map. The KMZ files that I've exported all work fine in ArcGIS Earth.

**Comment by BobBooth** [comment] 2018-02-15 21:08
So, for example, if I draw this set of shapes using different tabs:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/e7ade5a5-07b0-457e-91be-73aa04ff89b1)
Then, while on the Rings tab, export to KMZ, I get the three range rings, but not any of the other graphics.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/41849be6-f4fc-4098-b539-8f6b3dec7af4)
I think this behavior makes sense.
KMZ export seems to be working correctly.

**Comment by topowright** [comment] 2018-02-15 23:40
Verified
![image](https://user-images.githubusercontent.com/5488313/36286885-918a0a90-1266-11e8-82d9-8f4cc85016a2.png)

**Comment by topowright** [comment] 2018-02-15 23:42
[KMZ.zip](https://github.com/Esri/distance-direction-addin-dotnet/files/1729768/KMZ.zip)

**Comment by topowright** [comment] 2018-02-16 08:04
I do not think I closed this with the team. I am also seeing extra files when we export, but that is also captured in this issue
https://github.com/Esri/distance-direction-addin-dotnet/issues/401

**Closed** 2018-02-21 22:16 UTC
Labels: A-bug, E-non reproducible
