### ISSUE TITLE
Ring radials and Lines are not created as geodetic lines in ArcGIS Pro

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#180] opened 2016-12-15 17:38 UTC
_From @elinz on December 5, 2016 18:51_

The radials are not created as geodetic lines. 

We know that at least for 1.2 and 1.3 we can't create geodetic lines so the "Number of Radials" parameter should be hidden/disabled or removed.

![image](https://cloud.githubusercontent.com/assets/4635490/20897769/8e42eb72-bad8-11e6-8a93-bdcaa096d51b.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: ArcGIS Pro 1.3.0 final
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Windows 8.1 Enterprise 64 bit.
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#68_

**Comment by lfunkhouser** [comment] 2016-12-15 17:38
_From @kgonzago on December 9, 2016 13:41_

@elinz Can you test this with Pro 1.4? If issue persists, we will have to remove this functionality from the release.

fyi @lfunkhouser

**Comment by lfunkhouser** [comment] 2016-12-15 17:38
_From @elinz on December 9, 2016 16:8_

@kgonzago I installed the latest build Military Tools for ArcGIS that i believe was built on 1.3 SDK and I get the same incorrect results.

**Comment by mfunk** [comment] 2016-12-19 17:08
Still an issue at Pro 1.4

**Comment by pHill5136** [comment] 2016-12-19 22:49
@nfeuerstein @kgonzago I hid the radials label and text box on range rings and commented out the lines tab. pull request #193

**Comment by mfunk** [comment] 2016-12-20 15:41
@pHill5136 do we keep this one open to address geodetic lines in a future version of Pro, or close it out along with #181 (which seems a duplicate of this one). I'm for keeping this one open with milestone as Version - Deferred.

**Comment by pHill5136** [comment] 2016-12-20 16:26
@mfunk I think keep this one open. I removed the lines tab and hid the radials dialog in range rings per this thread. So I think we will want someone to verify those fixes...

**Comment by mfunk** [comment] 2016-12-20 17:51
@pHill5136  I verified the other one. Lines tab is gone and Radials is removed from Rings tab.

**Comment by mfunk** [comment] 2016-12-20 18:14
Looking in the Pro SDK API Reference there is reference to CurveType enumeration with members "Geodesic", "GreatElliptic", "Loxodrome", and "NormalSection" in ArcGIS.Core.Geometry Namespace.

https://pro.arcgis.com/en/pro-app/sdk/api-reference/#topic7844.html

This guy is used in GeometryEngine's GeodeticDensifyByLength Method:
https://pro.arcgis.com/en/pro-app/sdk/api-reference/#topic8245.html

From the method doc it seems that it basically modifies an existing geometry as one of the four input curve types.

**Comment by pHill5136** [comment] 2016-12-20 18:39
@kgonzago @nfeuerstein I hid fields for creating the radial lines. Noticed that since Pro and Arcmap addins share the dialog view that radials are turned off in ArcMap as well. Do we need to make separate viewmodels for rangerings?

**Comment by pHill5136** [comment] 2016-12-20 18:40
@kgonzago @nfeuerstein Sorry I meant to say separate views for range rings?

**Comment by kgonzago** [comment] 2016-12-20 19:21
@pHill5136 I believe you do. @jmccausland can provide more insight into this issue.

**Comment by jmccausland** [comment] 2016-12-20 19:50
I would bind the views xaml element visible property to a property in the view model.  Then in each view model since you already have one for each product, set those visibility properties in the view models constructor.  I believe we are already doing this somewhere.

**Comment by jmccausland** [comment] 2016-12-20 19:57
ProLineViewModel.cs has an example

`public System.Windows.Visibility LineTypeComboVisibility
        {
            get { return System.Windows.Visibility.Visible; }
        }`

**Comment by pHill5136** [comment] 2016-12-22 16:42
@nfeuerstein @topowright @elinz @kgonzago @mfunk Fixed geodesic lines and radials in Pro. Should show up in next build...

**Comment by ACueva** [comment] 2016-12-22 17:04
Build is kicking off right now,  should see the changes in a few minutes.

**Comment by mfunk** [comment] 2016-12-22 17:55
Going to test now...

**Comment by mfunk** [comment] 2016-12-22 18:31
So here is our Lines (Geodesic) and Range Ring (with Radials) in Pro with a Mercator projection (no, not Web Mercator). What I am expecting to see is Lines that bend (Geodesic) and Radials that are straight (they define a bearing and are therefore loxodromes). Loxodromes are straight in a Mercator projection.
![image](https://cloud.githubusercontent.com/assets/3093182/21435461/e48c0122-c82e-11e6-8b0f-d8114efe1b73.png)

WOOHOO!

Now if we use WGS 1984....
![image](https://cloud.githubusercontent.com/assets/3093182/21435830/ac636e5a-c830-11e6-8d37-6111be198579.png)
We get some weirdness going across the dateline.

In another projected ... Robinson (think National Geographic's world maps):
![image](https://cloud.githubusercontent.com/assets/3093182/21435741/410e52aa-c830-11e6-8415-294c6f998312.png)

Back to another GCS, this time GRS 1980:
![image](https://cloud.githubusercontent.com/assets/3093182/21435984/4027c6f4-c831-11e6-9053-9b807b11fe69.png)

So I don't think this is a problem with our tool, but in how line geometry is handled crossing the dateline in a Geographic Coordinate System. I'm going to close this issue as fixed, and log a new one to investigate this new issue further.

**Comment by elinz** [comment] 2017-02-14 21:41
The dateline issue was fixed, but the original problem where radials are not being created as geodetic was not fixed. The dateline issue should have been created as a separate issue. Reopening issue.

**Comment by pHill5136** [comment] 2017-03-14 21:28
Radials are created as Loxodromes so are straight in mercator projections. Should see distortion in non mercator projections....

**Comment by Dbarnes1** [comment] 2017-03-14 21:40
I guess the question is whether radials should be loxodromes or geodetic lines?

**Comment by mfunk** [comment] 2017-03-15 13:46
**NOT** Geodetic. They are intentionally created as Loxodromes which show lines of constant bearing. The whole idea of the radials is that they show a direction from the center to it's outside ring. Instead of defining what bearing to draw for each radial we simply take the number the user wants to draw, divide by 360 to find the interval, then start the first one at 0 degrees north, etc.

**Comment by pHill5136** [comment] 2017-05-12 17:14
lines should be straight in mercator projections. They are loxodromes (constant bearing).

**Comment by dfoll** [comment] 2017-05-19 17:19
after reading the comments on this, this issue should be closed. The issue is actually opposite of what what originally logged. Opening a new issue to reflect what was originally logged.

**Closed** 2017-05-19 17:19 UTC
Labels: 0 - Backlog, 3 - Verify, B - Bug, F - rings, V - Pro 1.4
