### ISSUE TITLE
Distance and Direction range rings tab values are cleared (except for Number of Rings) on creation

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#636] opened 2018-10-26 21:04 UTC
#### Current behavior
When creating range rings with radials using the Origin or Cumulative methods, if I set a center-point, add distances, type a value for the number of radials, and hit Enter to execute the creation of the rings, the rings and radials are created correctly, but the value is cleared (set back to 0) in the Number of Radials box, but not in the distance boxes.  
![image](https://user-images.githubusercontent.com/3801392/47592340-e7822300-d940-11e8-8754-7c795d886387.png)

#### Expected behavior
The number of radials should remain, in case I want to select a new location and add another set of rings and radials using the same settings.

**Comment by csmoore** [comment] 2019-01-03 14:00
This is the behavior of all the other tabs - that all of the values are cleared when you hit enter - so this change might be inconsistent with that behavior

**Comment by dfoll** [comment] 2019-04-09 14:02
`CT-Awaiting response` because it is unclear from this issue what exactly we are asking @CTLocalGovTeam to do for us

**Comment by dfoll** [comment] 2019-04-17 11:27
@lfunkhouser I want to push this issue to later in the future, as the team still doesn't have a consistent idea across the board of how we want the add-ins to behave. Thoughts?

**Comment by lfunkhouser** [comment] 2019-09-13 14:37
Closing. Current functions as designed across the tabs. Will revisit when we look at the entire add-in behavior.

**Closed by lfunkhouser** 2019-09-13 14:37 UTC
Labels: A-feature, E-as designed, F - rings
