### ISSUE TITLE
ArcGIS Pro becomes unresponsive after adding multiple DD line input points quick succession

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#621] opened 2018-07-05 15:28 UTC
When first using the Distance and Direction Line tool after having used the visibility tools (RLOS or LLOS on the visibility tab) if you click the input points button and click on the map multiple times in quick succession to add a few points (as if making two or three lines in a hurry), Pro locks up with the Loading Required Layer Package message.

Steps:
1) Add a raster (I used the UTM Zone 10N elevation raster in the test data).
2) Open Visibility tab and click LLOS.
3) Add an observer and a target point, run the LLOS operation.
4) Click the Distance and Direction tab.
5) Click the line tab.
6) Click the point input tool and click on the map multiple times in quick succession to add a few points, as if making two or three lines in a hurry.
Pro locks up with the Loading Required Layer Package message.

CPU usage varies up and down by about a percentage point, in fractions of a percent. RAM does not seem to change. 
Oddly, it seems like the layer package gets loaded, because my first line actually shows up on the display.
![image](https://user-images.githubusercontent.com/3801392/42332250-85263f92-8045-11e8-92aa-8b1f6786aedb.png)

This does not seem to happen if the package has been loaded before, even if you remove the layers from the TOC.
It does happen again if you delete the feature datasets containing the schema from the project GDB.
It does not seem to affect circle, ellipse, or rings tabs.

Using ArcGIS Pro 2.2.0 and Military Tools 3.0.0.76

**Comment by lfunkhouser** [comment] 2018-07-05 22:46
I'm not able to reproduce this issue. Tested on ArcGIS Pro 2.1 (MT 3.0.0.75) and ArcGIS Pro 2.2 (MT 3.0.0.76) Closing.

**Comment by BobBooth** [comment] 2018-07-06 14:23
I'm still seeing it.  It seems to happen after you've used the Visibility tools (both RLOS and LLOS). I suspect some sort of GDB locking issue.
It is sort of like https://github.com/Esri/visibility-addin-dotnet/issues/290 in that respect.
LLOS:
![image](https://user-images.githubusercontent.com/3801392/42383764-3b12d6d8-8106-11e8-8e29-23d54057b4c4.png)
RLOS:
![image](https://user-images.githubusercontent.com/3801392/42383881-993026bc-8106-11e8-8e39-ca173b074767.png)

**Comment by lfunkhouser** [comment] 2018-07-06 16:31
@BobBooth Please update the original description for clarity with the listed steps to reproduce.

**Comment by BobBooth** [comment] 2018-07-06 16:42
@lfunkhouser - done

**Comment by topowright** [comment] 2018-08-30 23:48
@CTLocalGovTeam now that we are using the same default project database the open edit session that ArcGIS Pro has by default is possibly creating this issue. We need to make sure when we are done with analysis we have to make sure to save the edits. This should be enough.

**Comment by dfoll** [comment] 2018-11-05 19:34
MT build 126 or later should be able to be used to test this

**Comment by dfoll** [comment] 2018-11-05 19:49
I cannot replicate this with MT build 126. @BobBooth  can you please try to repro with MT build 126. And see if this is no longer happening, given you  originally experienced this? If it looks to be fixed, we can proceed with the doc tasks

**Comment by BobBooth** [comment] 2018-11-05 20:22
@dfoll - I cannot replicate this on MT build 126. I think OK to proceed with the doc tasks.

**Comment by BobBooth** [comment] 2018-12-14 18:30
Military Tools What's new
Moved Issue 621 from know issues to issues addressed. h

Distance and Direction January 2019 
Moved Issue 621 from know issues to issues addressed.

**Comment by dfoll** [comment] 2018-12-18 18:56
verified @BobBooth changes in pdf and of dev pages. noticed the navigation.yml for DD needed updated while I was there, created [PR](https://github.com/ArcGIS/arcgis-solutions-website/pull/7348).

**Closed** 2018-12-20 20:43 UTC
Labels: A-bug, B-moderate, E-verified, F - lines, S-Military Tools, V -  Pro 2.1, V - 10.3.1, V - MT 3.3
