### ISSUE TITLE
Creating a line from distance and bearing - angle warning - ArcMap

### ISSUE THREAD

**Issue by joebayles** [Esri/distance-direction-addin-dotnet#246] opened 2017-01-06 22:21 UTC
When adding the angle, if the angle exceeds 360 degrees, it still renders a line. In it's defense, 2700 degrees really is 180 degrees, but I think it should at least show a warning.

**Comment by dfoll** [comment] 2017-01-14 23:57
This is something that should be added to the validation based on the selection of mils or degrees. Good Catch

**Comment by rjones0** [comment] 2017-01-25 16:59
I have a fix for this locally, will make a pull request when possible.

**Comment by rjones0** [comment] 2017-01-27 12:47
PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/305

**Comment by lfunkhouser** [comment] 2017-04-28 13:03
Assigning to @joebayles  who originally submitted the issue and the MT PEs to verify.

**Comment by topowright** [comment] 2017-04-28 22:51
This is still an issue. 
We should have the same interaction that happens in the Visibility Add in when an angle is put in that is higher than 360

![image](https://cloud.githubusercontent.com/assets/5488313/25549961/11287b0c-2c2a-11e7-9e26-2bbd22c37f6c.png)

This should be done when using degrees for one and for mils it would be 6400 mil. From my research that is that amount of mils in a circle. If I am wrong the tool should turn red when the number exceeds the equivalent of 360 degrees

**Comment by topowright** [comment] 2017-04-28 23:04
Saw that this covered ArcMap and I found the following error with the verification: 

![image](https://cloud.githubusercontent.com/assets/5488313/25550219/3ddfd044-2c2c-11e7-9788-0d1d74f77ece.png)

ArcGIS Pro does not conduct any validation. I think this issue should cover ArcMap and ArcGIS Pro. 

@pHill5136 FYI; thought you would care based on the pull request that you merged.

**Comment by lfunkhouser** [comment] 2017-05-02 03:55
Assigning Devs - @csmoore and @kgonzago and adding ```backlog``` label

**Comment by csmoore** [comment] 2017-05-03 15:48
I wasn't exactly able to reproduce this issue, but I did notice some badness when distance=0 (as show in the screenshot), so added a check for that - can you retest in the next daily?  Reassigning for re-test.

I also noticed several other issues with the feedback graphic while testing this recorded in new issue #364

**Comment by ACueva** [comment] 2017-05-03 16:48
@csmoore I don't know, is this the output you were expecting?
![2017-05-03_9-47-23](https://cloud.githubusercontent.com/assets/3093940/25671641/9b228672-2fe5-11e7-9ae6-bf3f9ab8dcd0.png)

**Comment by NatalieCampos** [comment] 2017-05-03 20:18
verified.  values between 340-360 work.  values greater than 360 do not.

**Comment by NatalieCampos** [comment] 2017-05-04 17:37
This issue still isnt fixed.  The graphic still draws past 360.  It actually draws the last valid angle that was dynamically drawn.


![image](https://cloud.githubusercontent.com/assets/5116835/25716903/a7d3be56-30b5-11e7-9d7f-f04724ecf70e.png)

**Comment by csmoore** [comment] 2017-05-08 17:35
I have a change for this that resets the the feedback angle to zero (its initial state) - hopefully this will work to clear up the confusion above:

![image](https://cloud.githubusercontent.com/assets/3090809/25814038/e338f3e4-33e9-11e7-9654-11323d40205c.png)

**Comment by csmoore** [comment] 2017-05-09 16:44
This is ready for re-retest in the next build (with/note the behavior mentioned in the last comment)

**Comment by NatalieCampos** [comment] 2017-05-10 20:04
i got this one.

**Comment by NatalieCampos** [comment] 2017-05-10 20:16
Verified.  Any angle over 360 throws an invalid input

![image](https://cloud.githubusercontent.com/assets/5116835/25919213/e50fc220-3582-11e7-90ad-983d5e6f5f63.png)

**Closed by NatalieCampos** 2017-05-10 20:16 UTC
Labels: 3 - Verify, B - Bug, V - 10.3.1, V - Pro 1.4

**Comment by dfoll** [comment] 2017-05-12 17:37
This looks like it is fixed. If you start entering a value, say .... 4 then 0 it will draw a preview at 40 degrees. if you continue on to enter 5 (thus trying to create an angle of 405) you get the red X warning and it won't draw when you press enter. Closing this issue, however i am opening a new one, as it seems like mils is not working correctly, from my understanding 405 would be a valid angle when working with mils, but when i switch to mils, i still can not enter a value over 360.
