### ISSUE TITLE
Comma causes error message Range Rings tab in Distance and Direction but not on Circle tab

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#514] opened 2018-02-22 16:35 UTC
The logic used to parse input values on the Circle tab should also be used on the Rings tab for the Origin and Cumulative construction methods.
Decimal values work, but using a comma as a thousands separator causes the tool to give an "Ensure all distances are numeric" message.
![image](https://user-images.githubusercontent.com/3801392/36550784-19582620-17c4-11e8-97fc-87826a6d75df.png)

@adgiles @kgonzago

**Comment by BobBooth** [comment] 2018-02-22 16:53
@adgiles - maybe this could be fixed before @kgonzago PR gets merged into core?

**Comment by adgiles** [comment] 2018-02-22 17:01
With the changes I am currently making to the workflow you will be unable to put a comma into the box

**Comment by kgonzago** [comment] 2018-02-22 17:02
FYI, [PR](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11837) was merged.

**Comment by adgiles** [comment] 2018-02-22 17:18
the distances for the range values are now only going to accept numeric values

**Comment by kgonzago** [comment] 2018-02-22 18:11
Changes are now in a new [PR](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11887) created in Devtopia.

@BobBooth Can you test this [branch](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/tree/kevi2741-distance-and-direction)

**Comment by BobBooth** [comment] 2018-02-22 19:18
@kgonzago  - still seeing it with that one
![image](https://user-images.githubusercontent.com/3801392/36559177-34097444-17db-11e8-9b59-4b355d0020ab.png)

**Comment by adgiles** [comment] 2018-02-22 19:28
@bobbooth @kgonzago I’m going to have to look at this a bit more, the issue is the simple table dijit only accepts text as entries where we are using the number validation on other inputs. We now have to do the validation ourselves. 

It’s not just a case of removing commas from the inputs as in some languages comma’s are used as decimal points. My recommendation would be only to accept one comma or decimal point to be used to represent a decimal point value

**Comment by BobBooth** [comment] 2018-02-22 19:31
OK, so if I set the distance values to 4,000 meters and 5,000 meters, the tool does run, but it interprets the comma as a decimal point.
I get rings with 4.0 and 5.0 meter circles.
![image](https://user-images.githubusercontent.com/3801392/36559804-fe508502-17dc-11e8-9ccb-b34cfa67dad2.png)

If I set it to 33,000.5 - that is, a comma and a decimal point, then I get the "must be numeric" warning.
![image](https://user-images.githubusercontent.com/3801392/36559732-cc95df3a-17dc-11e8-9067-9b11bf3d82a5.png)
 
@kgonzago

**Comment by adgiles** [comment] 2018-02-22 19:43
@bobbooth yes at the moment it is thinking the comma is a decimal point, I need to do more work on this tomorrow

**Comment by BobBooth** [comment] 2018-02-22 19:48
The circle tool handles this case.
![image](https://user-images.githubusercontent.com/3801392/36560659-5f7d16ae-17df-11e8-8775-24653ad4ccf9.png)
Can we not pass the numbers from the table through the same validation code used by the circle tool?

**Comment by adgiles** [comment] 2018-02-22 20:13
No, they are using different components of the dojo framework

**Comment by adgiles** [comment] 2018-02-23 16:09
@bobbooth I have refactored the code i was using and managed to get the input boxes within the table to use the same input type as used within the circle tool. Once @kgonzago has pushed the changes up to devtopia you should be good to test.

**Comment by kgonzago** [comment] 2018-02-23 16:10
FYI: Changes were pushed to this [PR](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11887).  This [branch](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/tree/kevi2741-distance-and-direction) can be used for testing.

**Comment by BobBooth** [comment] 2018-02-23 16:50
@adgiles @kgonzago 
Tested this, getting error on launch widget:
![image](https://user-images.githubusercontent.com/3801392/36605761-b160938c-188f-11e8-8c26-da890c29c579.png)

Unfortunately, I'm heading out now for the weekend. See you Monday!

**Comment by ACueva** [comment] 2018-02-23 17:07
@kgonzago let's chat regarding code differences between internal and external GitHub repos.

**Comment by kgonzago** [comment] 2018-02-23 18:34
The widget didn't launch due to an additional semicolon. [Fixed](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11887/commits/3fda543f65fa48dcca30f96cef07343f9675f7f8) it in devtopia.

The widget in devtopia and this repo are now sync'ed using this [branch](https://github.com/Esri/distance-direction-addin-dotnet/tree/kg/wab-dev). The branch will not be merged with `dev` branch anytime soon.

**Comment by BobBooth** [comment] 2018-02-26 19:05
Commas, decimals, and mixed commas & decimals is working with this fix, in branch @kgonzago  mentioned (https://github.com/Esri/distance-direction-addin-dotnet/tree/kg/wab-dev).
See image:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/d391630b-33bf-41fe-bc39-dc1432f76792)

**Comment by dfoll** [comment] 2018-02-26 23:37
I looked at this as well and everything looks ok with the commas and decimals 
- was able to intentionally use both in a value
- was able to use just a comma (it adds the decimal point)
- was able to use no comma (it adds the comma and decimal after hitting enter)

**Comment by lfunkhouser** [comment] 2018-02-28 15:00
@BobBooth @dfoll Was the checklist test updated to test the variations?

**Comment by BobBooth** [comment] 2018-02-28 15:33
@lfunkhouser - I had a commit in one of the PRs that somehow got lost in the merging process. Have re-added that info and expanded. Asking @dfoll  to merge.
https://github.com/ArcGIS/solutions-defense-test-catalog/pull/94

**Comment by adgiles** [comment] 2018-03-01 17:10
@topowright @dfoll @ACueva

now showing in the daily build (01 Mar 18), good to test

**Comment by dfoll** [comment] 2018-03-05 21:52
-verified fixed with the daily
-verified the checklist test is updated to instruct the user to user commas and decimal points

**Closed** 2018-03-28 15:19 UTC
Labels: A-bug, B-moderate, F - circles, F - rings, V - WAB
