### ISSUE TITLE
ArcMap addin not creating KMZ features when using Save As.

### ISSUE THREAD

**Issue by pshowalter** [Esri/distance-direction-addin-dotnet#119] opened 2016-04-13 14:42 UTC
In ArcMap, when using Save As for Lines, Circle, Ellipse, and Rings, a KMZ file of 1KB is produced, but nothing displays when added to GE.  ArcMap Data frame is in Web Mercator.

**Comment by topowright** [comment] 2016-04-15 21:09
@dhagens do you think you can take a look at this. Is this a true bug?

**Comment by dhagens** [comment] 2016-04-21 15:47
I cannot reproduce the issue.  Will work with @pshowalter to see how he got this to fail.

**Comment by dhagens** [comment] 2016-04-21 17:13
I'm not sure what's going on on @pshowalter machine but this functionality works everywhere else.  I tested Line, Circle, Ellipse, and Range Rings and all worked fine on my machine using both a PCS and GCS basemap.  @jmccausland  also tested on his machine with no issues.  @mcalamito also tested on his machine and had no issues.  I will close this bug.

**Closed** 2016-04-21 17:19 UTC
Labels: B - Bug, B - Question
