### ISSUE TITLE
Range Rings output first KMZ is 'bad', second is fine.

### ISSUE THREAD

**Issue by mfunk** [Esri/distance-direction-addin-dotnet#329] opened 2017-02-21 23:16 UTC
1) Create Range Rings:
   - Center point approximately at 10.2 11.4
   - 10 Rings, 200 KM between, 5 Radials
2) Rings draw just fine in Pro 1.4.1
![image](https://cloud.githubusercontent.com/assets/3093182/23189428/b83d4b00-f847-11e6-9803-439fd50e3287.png)

3) **Save As** >> **KMZ**
4) Open *.kmz in Google Earth (features are not drawing as expected)
![image](https://cloud.githubusercontent.com/assets/3093182/23189351/5d835902-f847-11e6-86ae-33ac9fa33975.png)

5) Open *.kmz in Pro (extents are unreasonable)
![image](https://cloud.githubusercontent.com/assets/3093182/23189363/6f6034a6-f847-11e6-8d53-74356c066ef1.png)

Try it again:
6) run RR a second time and Save As >> KMZ again...
In Google Earth:
![image](https://cloud.githubusercontent.com/assets/3093182/23189613/9a2d0d16-f848-11e6-9f4e-de1ed78d7f03.png)

And again adding KMZ to Pro:
![image](https://cloud.githubusercontent.com/assets/3093182/23189591/82d5a466-f848-11e6-98db-7b586a4212b8.png)

**Comment by ACueva** [comment] 2017-05-19 17:45
I was able to reproduce this issue.  I've logged a case with Tech Support.  Esri Case #01933479
I believe this is going to be an issue with the Layer to KML geoprocessing tool in Pro.  Will update this issue once a bug has been logged.

**Comment by dfoll** [comment] 2017-05-19 18:04
@ACueva i have carried over this information to the relevant issue i had in Pro #299 When tech support opens an issue, please let me know so i can update #299 or feel free to update #299 yourself with the support issue details.

**Comment by lfunkhouser** [comment] 2017-12-30 02:48
Was there an issue logged with Tech Support? @ACueva have you followed up on this issue?

**Comment by BobBooth** [comment] 2018-04-20 18:04
Non-reproducible on Pro 2.1.0 with Military Tools build from 4/17/18.

**Comment by BobBooth** [comment] 2018-04-23 17:48
Checklist test updates merged.
@ACueva  - I think this is ready to move to Done.

**Comment by ACueva** [comment] 2018-04-23 18:06
This issue was fixed in CR: 353317.  @BobBooth's non-reproducible makes sense since this was fixed at Pro build 12.0.0.8136.
Switching label from E - Non Reproducible to E-Verified.

**Closed** 2018-04-30 21:38 UTC
Labels: A-bug, E-verified, F - rings
