### ISSUE TITLE
Line Graphic/Feedback issues on Line(Tab) in From:Distance and Bearing Mode

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#364] opened 2017-05-03 15:38 UTC
While testing #246 I noticed some other issues with the map feedback graphic:

Version: Lastest dev/daily
Tab: Line
Mode:  Distance and Bearing 

Issue 1:
In many circumstances, the feedback graphic does seem to update, the only sequence that works reliably is:
1. Select the Map Tool to set the Starting Point
2. Then change the Distance/Length

Issue 2:
Changing the Starting Point does not update the feedback graphic on the map using the existing Distance/Angle parameters (sometimes you can see the feedback graphic flash then disappear)

Issue 3: 
Switching Option "From: " from "Points" to "Distance and Bearing" does not use the existing Start Point value, you have to change the start point value and then distance/azimuth to get the feedback graphic to appear

Issue 4: 
The are scenarios where the feedback line does not clear itself properly from the previous operation and you 2 feedback lines or a flashing feedback line

Issue 5: 
Update - I didn't know you had to press enter from one of the textboxes ~~(Not sure if this is by design or an enhancement) there doesn't seem to be a way to create a permanent graphic in this mode (change the feedback graphic to permanent labeled graphic)~~

Screenshots:

Valid parameters but no feedback graphic:
![image](https://cloud.githubusercontent.com/assets/3090809/25667669/2c5eeaac-2ff2-11e7-93de-3a3431bf3316.png)

**Comment by pHill5136** [comment] 2017-06-15 14:50
please verify

**Comment by ACueva** [comment] 2017-06-15 15:27
@nfeuerstein Looks like this issue is ready to be tested.  It's labeled Version after next.  Please review and if appropriate move to version next.

**Comment by nfeuerstein** [comment] 2017-06-15 15:29
@pHill5136 can you provide some context please?

**Comment by pHill5136** [comment] 2017-06-15 16:05
@nfeuerstein I read the tag wrong. I've been looking at this one for a while now and found a solution.

**Comment by ACueva** [comment] 2017-06-15 22:01
@pHill5136 Kicking it back, still appears to be an issue in Pro.

**Comment by ACueva** [comment] 2017-06-16 22:10
@pHill5136 It's still not honoring the following in ArcGIS Pro:

Issue 2:
Changing the Starting Point does not update the feedback graphic on the map using the existing Distance/Angle parameters (sometimes you can see the feedback graphic flash then disappear)

Let me know if you want me to step through it with you.

**Comment by pHill5136** [comment] 2017-06-21 15:06
Please verify. The behavior now is that you have to create the map point 1st before you populate the distance and azimuth.

**Comment by NatalieCampos** [comment] 2017-06-22 15:51
Issue 2 has been fixed.  working to verify other issues

**Comment by NatalieCampos** [comment] 2017-06-22 16:34
@csmoore I cant reproduce  issue 1.  I think the fix @pHill5136 implemented might have solved this problem. Continuing to work on other issues.

**Comment by NatalieCampos** [comment] 2017-06-22 17:01
Issue 3:  After entering a start point with From Point as the draw method and then switch to Distance and Bearing ... the original starting point disappears.  I see nothing wrong with this behavior.... again I think this might be related to @pHill5136 fix.

**Comment by NatalieCampos** [comment] 2017-06-22 17:01
Issue 4:  in the testing of issues 1-3, I have not seen this occur.  For now I will close this issue as verified.

**Closed by NatalieCampos** 2017-06-22 17:01 UTC
Labels: 3 - Verify, B - Bug, effort-extra large
