### ISSUE TITLE
Circle tool - created graphic is not labeled (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#255] opened 2017-01-11 22:20 UTC
build 11 Jan 2017 13:51 of ArcGIS Pro addin. Circles are not labeled. 
![image](https://cloud.githubusercontent.com/assets/4635490/21868721/0ec70f74-d809-11e6-9a75-ad018b8dacc4.png)

**Comment by elinz** [comment] 2017-01-11 22:35
Here's how it looks in ArcMap:
![image](https://cloud.githubusercontent.com/assets/4635490/21869176/28de1f5e-d80b-11e6-9730-76b905f9a4bc.png)

**Comment by Dbarnes1** [comment] 2017-01-12 00:50
I can duplicate these labeling issues.

**Comment by dfoll** [comment] 2017-01-14 23:41
We are able to create labels on the top of targets in ArcGIS Pro using the Visibility add-in. We should look at this as a possible way forward.

**Comment by mfunk** [comment] 2017-02-13 19:00
Duplicate of earlier issue: https://github.com/Esri/distance-direction-addin-dotnet/issues/192

**Comment by nfeuerstein** [comment] 2017-05-18 16:44
Labels are still a limitation in Pro.

**Comment by lfunkhouser** [comment] 2018-04-25 03:35
Closing. Graphics are not labeled in ArcGIS Pro. #540 has been created to handle the labels on created circles.

**Closed by lfunkhouser** 2018-04-25 03:35 UTC
Labels: A-bug, B - Known Issue, D-ArcGIS Pro, F - circles
