### ISSUE TITLE
Distance and Direction Ring [and ellipse] tool incorrectly labels the distance between rings at certain zoom scales

### ISSUE THREAD

**Issue by ACueva** [Esri/distance-direction-addin-dotnet#552] opened 2018-04-20 21:59 UTC
### Version:

ArcGIS Desktop 10.6 Final
Military Tools 3.0 build 39

### Steps to reproduce:

1. Open ArcMap and add a basemap.
2. Open the Distance and Direction add-in.
3. Select Rings.
4. Make sure you are not in iterative mode. (checked off)
5. Enter number of rings: 10
6. Enter distance between rings: 100
7. Select unit of measure: default is meters
8. Enter number or radials: 5
9. Using the map point tool, select a point.
10. Click enter.

Results come in with the label upside down.
![2018-04-20_13-53-26](https://user-images.githubusercontent.com/3093940/39074677-41520bea-44a7-11e8-8919-adbf6589fd27.jpg)

When you zoom in, the labels appear fine.
![2018-04-20_14-31-20](https://user-images.githubusercontent.com/3093940/39074748-84e6ee3e-44a7-11e8-98aa-70efc1c69df0.jpg)

**Comment by lfunkhouser** [comment] 2018-07-05 23:07
@BobBooth I agree. Setting scale-dependent rendering would make for a cleaner map display at a super zoomed out scale.

**Comment by dfoll** [comment] 2018-11-30 16:20
@lfunkhouser @BobBooth wondering what we want to do with this one. This was listed as a known issue in sept, it is not listed in january. my opinion is that this issue would be resolved with an enhancement, but is not actually a known issue. question is do we include it as a known issue for jan or not?

**Comment by lfunkhouser** [comment] 2018-12-05 18:41
Not a bug. Added feature enhancement for cleaner map display. @dfoll agree that this should be removed from Jan and not listed as a known issue.

**Comment by lfunkhouser** [comment] 2019-09-13 14:21
Will not address.

**Closed by lfunkhouser** 2019-09-13 14:21 UTC
Labels: A-feature, G-Development
